### ISSUE TITLE
Write README.md for this repository

### ISSUE THREAD

**Issue by lambiengcode** [lambiengcode/nodejs_express_template#2]
- How to use and customize
- How I can run it?
- How I can write more

**Comment by aditya28sarin** [comment]
Can you assign this issue to me?

**Comment by lambiengcode** [comment]
Glad if you help me, I will invite you to this repository

**Comment by aditya28sarin** [comment]
I have created a readme

**Comment by lambiengcode** [comment]
Good job, I will close the issue
